const FoodsItem = [
  {
    id: 1,
    image: "./Breakfast/breakfast1.png",
    price: 15,
    title: "Egg Benedict",
    desc: "Extended local parallelism",
    category: "breakfast",
  },

  {
    id: 2,
    image: "./Breakfast/breakfast2.png",
    price: 13,
    title: "Breakfast sandwitch",
    desc: "Centralized contextually-based software",
    category: "breakfast",
  },
  {
    id: 3,
    image: "./Breakfast/breakfast3.png",
    price: 10,
    title: "Baked Chicken",
    desc: "Synchronised exuding instruction set",
    category: "breakfast",
  },
  {
    id: 4,
    image: "./Breakfast/breakfast4.png",
    price: 12,
    title: "Bagel and Cream Cheese",
    desc: "Triple-buffered cohesive infrastructure",
    category: "breakfast",
  },
  {
    id: 5,
    image: "./Breakfast/breakfast5.png",
    price: 18,
    title: "Full Breakfast Fried Egg Toast Brunch",
    desc: "Polarized value-added policy",
    category: "breakfast",
  },
  {
    id: 6,
    image: "./Breakfast/breakfast6.png",
    price: 16,
    title: "Toast Croissant",
    desc: "Customer-focused real-time access",
    category: "breakfast",
  },
  {
    id: 7,
    image: "./lunch/lunch1.png",
    price: 23,
    title: "Honey-Soy-Glazed salmon with Peppers",
    desc: "Open-source actuating time-frame",
    category: "lunch",
  },
  {
    id: 8,
    image: "./lunch/lunch2.png",
    price: 20,
    title: "Tarragon-Rubbed-Salmon",
    desc: "Versatile heuristic application",
    category: "lunch",
  },
  {
    id: 9,
    image: "./lunch/lunch3.png",
    price: 29,
    title: "Indian Lunch",
    desc: "Enhanced national throughput",
    category: "lunch",
  },
  {
    id: 10,
    image: "./lunch/lunch4.png",
    price: 25,
    title: "Fried Chicken Bento",
    desc: "Team-oriented stable info-mediaries",
    category: "lunch",
  },
  {
    id: 11,
    image: "./lunch/lunch5.png",
    price: 28,
    title: "Healthy Meal Plan",
    desc: "Advanced needs-based task-force",
    category: "lunch",
  },
  {
    id: 12,
    image: "./lunch/lunch6.png",
    price: 21,
    title: "Beef Steak",
    desc: "Multi-tiered content-based superstructure",
    category: "lunch",
  },
  {
    id: 13,
    image: "./Dinner/dinner1.png",
    price: 20,
    title: "Beef vuna",
    desc: "Persistent fresh-thinking help-desk",
    category: "dinner",
  },
  {
    id: 14,
    image: "./Dinner/dinner2.png",
    price: 18,
    title: "Lemony Salmon Piccata",
    desc: "Polarised interactive internet solution",
    category: "dinner",
  },
  {
    id: 15,
    image: "./Dinner/dinner3.png",
    price: 25,
    title: "Garlic Butter Baked Salmon",
    desc: "Polarised object-oriented concept",
    category: "dinner",
  },
  {
    id: 16,
    image: "./Dinner/dinner4.png",
    price: 26,
    title: "French Fries with cheese",
    desc: "Function-based clear-thinking knowledge user",
    category: "dinner",
  },
  {
    id: 17,
    image: "./Dinner/dinner5.png",
    price: 36,
    title: "Pork Tenderloin With Quinoa Pilaf",
    desc: "Compatible asynchronous help-desk",
    category: "dinner",
  },
  {
    id: 18,
    image: "./Dinner/dinner6.png",
    price: 22,
    title: "Salmon with Grapefruit and Lentil Salad",
    desc: "Switchable methodical pricing structure",
    category: "dinner",
  },
];

export default FoodsItem;
